version: '3.8'

services:
  smarthome:
    container_name: smarthome_container
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    stdin_open: true
    env_file:
      - ./.env
    depends_on:
      - db
      - pgadmin
      - minio
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    restart: 
      always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3003:3003'
    networks:
      - backend
    command: npm run start:dev

  db:
    image: postgres
    restart: always
    ports:
      - '6000:5432'
    expose:
      - 6000
    environment:
      POSTGRES_DB: training-app
      POSTGRES_PASSWORD: 123456789
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '80:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: tduy0215@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    networks:
      - backend
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: tduy0215@gmail.com
      MINIO_ROOT_PASSWORD: 123456789
    command: server --console-address ":9001" /data
    networks:
      - backend
  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - 'mongodb_master_data:/bitnami/mongodb'
    ports:
      - '27017:27017'
    networks:
      - backend
  mongodb-secondary:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - backend
  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - backend
volumes:
  db_data:
  minio_storage: {}
  mongodb_master_data:
    driver: local
networks:
  backend:
    name: backend
    external: true